### PR TITLE
Reproduce inference

### PR DESCRIPTION
**Pull request by lemswasabi**
# What does this PR do?

This PR deals with the Assignment 7 of the VT Programming class. It reproduces an ASR task using the wav2vec 2.0 Transformer model implemented in the Huggingface library. The PR contains the following artifacts:

- README.md file with the corresponding instructions
- .py script file for inference
- .ipynb notebook file for inference
- requirements.txt for dependencies management

## Possible reviewers:

@phat-vtcf @AmarensElise

### CODE REVIEW

**Comment by cmfuego** [comment]
Hi @Tatsu1020 and @Lemswasabi,

Your readme file is very clear on what your task was and how to reproduce it in different ways (locally and in colab). 

The notebook is also overall clear and very easy to replicate! I uploaded our own 'North wind and the sun' recordings and calculated the WERs without problems.
Locally I could sadly not reproduce the task because I did not get the python_Levenshtein package to work for jiwer, but I did not use a virtual environment. The code itself looks good.

For the purpose of this assignment it might have been helpful if you would have included the location of your added files in your PR description. We found your files by viewing the commit history, but the folder 'notebooks' is not an extremely obvious place to store all your files.

Overall I think your pull request looks good and is ready to be merged!

**Comment by AmarensElise** [comment]
Hi @Tatsu1020 and @Lemswasabi,

I agree with @cmfuego, I couldn't immediately locate the files, but through the branch history, we were able to find them. The README is clear on what it does, where and how it could be run, and what the output will be. I also couldn't get it to run locally, but through the colab notebook it worked perfectly. Very interesting to see our own WER! 

Well done guys!

**Comment by lemswasabi** [comment]
> Locally I could sadly not reproduce the did not get the python_Levenshtein package to work for jiwer, but I did not use a virtual environment. The code itself looks good.

@cmfuego That's interesting, could you share with us the error output so I could have a look at it?

> For the purpose of this assignment it might have been helpful if you would have included the location of your added files in your PR description.

I agree with you both, that for the setting of this assignment it would be better to include the location of the PR's artefacts. I chose the `notebooks` directory because this made the most sense if this would be a real PR to the real repository.

This could be a tip for your future PRs: When you are assigned for a requested review, you will see a yellow banner before the title of the PR. This banner will display a green button `Add your review`. The button will take you to a page where you can see the PR's changed files and the directory containing them. @AmarensElise since you are the only assigned reviewer, you are the only one seeing this banner. AFAIK, you can only merge a PR after marking the changed files as `viewed`.

**Comment by cmfuego** [comment]
> @cmfuego That's interesting, could you share with us the error output so I could have a look at it?

image

I encountered this problem a few weeks earlier for another package. After googling I found that it might help to install the C++ Build Tools using Visual Studio Installer from the link in the error message. However that turned out to be almost 7 GB and I wanted to look into it a bit further before doing that. Do you have some ideas about this?

But as I mentioned earlier: this is a problem of my own and not caused by the way you documented things!

**Review by AmarensElise — APPROVED** [review]

**Comment by lemswasabi** [comment]
> I encountered this problem a few weeks earlier for another package. After googling I found that it might help to install the C++ Build Tools using Visual Studio Installer from the link in the error message. However that turned out to be almost 7 GB and I wanted to look into it a bit further before doing that. Do you have some ideas about this?

Thank you @cmfuego for the error message, I looked it up and this is a problem related only to the Visual C++ package made by Microsoft:
> When you use the pip command to install the library, you will need to compile it during the installation process. However, the Windows environment you are using does not have the required version of the compiler.

As you said this is not related to the dependency management of this PR. Nevertheless, I think installing the dependencies in a Conda environment through the Windows command prompt should do the job.

@AmarensElise Thanks for the review approval. From my side, everything should be set. You will get a grade from @Tatsu1020  and then you can merge the PR.

**Comment by lemoncakeee** [comment]
Hi @AmarensElise and @cmfuego,

We give the grade for your reviews here! We assessed your reviews based on the following criteria: fairness, clearness and reproducibility, and helpfulness. 

1. Fairness - 10 points
You have given very fair reviews. We should have specified the file location for this assignment to make it easier to review our work.

2. Clearness and reproducibility - 9.5 points
It would have been better if you could give us more detail description what the error was and how you encountered the error. This would have been more helpful for us to solve the problem that you faced!

3. Helpfulness - 10 points
You have been helpful to solve the error that you encountered by replying to our comments patiently. We appreciate your helps! 

Overall grade - 9.83
@phat-vtcf Based on the above mentioned assessments, we would like to give them 9.83 as a overall grade.

**Pull request merged**
